server {
    listen 8080;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /config.js {
        default_type application/javascript;

        return 200 "window.APP_CONFIG = {
            VITE_API_TOKEN: '${VITE_API_TOKEN}',
            VITE_FIREBASE_API_KEY: '${VITE_FIREBASE_API_KEY}',
            VITE_FIREBASE_AUTH_DOMAIN: '${VITE_FIREBASE_AUTH_DOMAIN}',
            VITE_FIREBASE_PROJECT_ID: '${VITE_FIREBASE_PROJECT_ID}',
            VITE_FIREBASE_STORAGE_BUCKET: '${VITE_FIREBASE_STORAGE_BUCKET}',
            VITE_FIREBASE_MESSAGING_SENDER_ID: '${VITE_FIREBASE_MESSAGING_SENDER_ID}',
            VITE_FIREBASE_APP_ID: '${VITE_FIREBASE_APP_ID}'
        };";
    }
}
