name: Deploy Server

on:
  push:
    paths:
      - "server/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_NAME: ci-cloud-run
      REGION: europe-west1

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker

      - name: Build, tag, and push image to GCR
        id: build-image
        working-directory: server
        run: |
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/codeway-case/server:${{ github.sha }} .
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/codeway-case/server:latest .
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/codeway-case/server:${{ github.sha }}
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/codeway-case/server:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.GCP_PROJECT_ID }}/codeway-case/server:latest
          region: ${{ env.REGION }}
          credentials: ${{ secrets.GCP_SA_KEY }}
