name: Deploy Server

on:
  push:
    paths:
      - "server/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_NAME: ci-cloud-run
      REGION: europe-west1

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "my-service-account@my-project.iam.gserviceaccount.com"

      - name: Log in to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build, tag, and push image to GCR
        id: build-image
        working-directory: server
        run: |
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/codeway-case/server:${{ github.sha }} .
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/codeway-case/server:latest .
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/codeway-case/server:${{ github.sha }}
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/codeway-case/server:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.GCP_PROJECT_ID }}/codeway-case/server:latest
          region: ${{ env.REGION }}
          credentials: ${{ secrets.GCP_SA_KEY }}
